### ISSUE TITLE
Allow type name to include only 2 tokens

### ISSUE THREAD

**Issue by rjlohan** [aws-cloudformation/aws-cloudformation-resource-schema#7]
To support certain partners or types where an Organization::Service::Resource namespace is hard to fulfil. Simple example; `AWS::::Account`

**Comment by PatMyron** [comment]
[While custom resources have unfortunately already broken this assumption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cfn-customresource.html#aws-resource-cfn-customresource--remarks), I think it'd be simpler to avoid expanding to allow more uncommon unexpected resource type name patterns, especially since CloudFormation template recognition frequently relies on resource type patterns since [`AWSTemplateFormatVersion`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html) is optional: https://github.com/aws-cloudformation/cfn-python-lint/issues/1171, https://github.com/aws-cloudformation/aws-cfn-lint-visual-studio-code/issues/99, https://github.com/aws/aws-toolkit-jetbrains/pull/1715#discussion_r421074217, https://github.com/github/super-linter/pull/231#discussion_r445708695, https://github.com/mwpearce/vscode-cfn-nag/issues/6, https://github.com/joenye/coc-cfn-lint/issues/3#issuecomment-678843159

The public `AWS::::Account` resource type will likely just be [`AWS::Organizations::Account`](https://docs.aws.amazon.com/cli/latest/reference/organizations/create-account.html)

Some other resource types might be a bit more odd, but we should be able to find something suitable for them
