### ISSUE TITLE
Translating Cloudformation Resources to API Calls

### ISSUE THREAD

**Issue by eitens-mak** [aws-cloudformation/aws-cloudformation-resource-schema#99]
I want to read a Cloudformation template and translate the resources into the API calls needed to create them. Can I use this package somehow to do this?

**Comment by PatMyron** [comment]
Parsing the [`create handler permissions`](https://github.com/aws-cloudformation/aws-cloudformation-resource-schema#permissions) from the respective [hosted resource provider schemas](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-type-schemas.html) should find the maximum possible API permissions required. Not all create handler API permissions listed in the schema may be required in all scenarios though

There are some similar projects around this space as well:
https://github.com/stelligent/cfn-leaprog
https://github.com/iann0036/aws-leastprivilege

**Comment by eitens-mak** [comment]
I was thinking more along the lines of converting a Cloudformation template to API calls or AWS CLI commands.

**Comment by PatMyron** [comment]
> I was thinking more along the lines of converting a Cloudformation template to API calls or AWS CLI commands.

This wouldn't be deterministic from a CloudFormation template alone. The API calls required depend on the previous CloudFormation stack state in some cases if updating a stack rather than creating. Assuming the simpler case of creating a new stack, the `CreateHandler`s themselves are [beginning to be open sourced](https://github.com/aws-cloudformation?q=aws-cloudformation-resource-providers-&type=public) (along with the other handlers as well). As a specific example, [`handleRequest`](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-logs/blob/82451dd6f21b7f7edf049a6cbe063f9b3940ffe6/aws-logs-loggroup/src/main/java/software/amazon/logs/loggroup/CreateHandler.java#L20) in [`AWS::Logs::LogGroup`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html)'s [`CreateHandler`](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-logs/blob/master/aws-logs-loggroup/src/main/java/software/amazon/logs/loggroup/CreateHandler.java) can be viewed as an entry point to creating [`AWS::Logs::LogGroup`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html) resources
